version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "build"
      include: scope
    groups:
      maven-plugins:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns: ["*"]
